steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMAGE_NAME}:${BUILD_ID}'
    - '-t'
    - '${_IMAGE_NAME}:latest'
    - '.'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - '${_IMAGE_NAME}'

substitutions:
    _IMAGE_NAME: us-central1-docker.pkg.dev/${PROJECT_ID}/docker/phonebook

options:
    dynamic_substitutions: true

images:
- ${_IMAGE_NAME}
